name: "Bump Version"

on:
  push:
    branches:
      - "main"

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history for changelog
      - name: Androlax2 Gitmoji Changelog Action
        uses: Androlax2/gitmoji-changelog-action@main
